
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import LendingContractArtifactJson from '../../target/lending_contract-Lending.json' assert { type: 'json' };
export const LendingContractArtifact = loadContractArtifact(LendingContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Lending;
 */
export class LendingContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, LendingContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, LendingContract.artifact, wallet) as Promise<LendingContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<LendingContract>(PublicKeys.default(), wallet, LendingContractArtifact, LendingContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<LendingContract>(publicKeys, wallet, LendingContractArtifact, LendingContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof LendingContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<LendingContract['methods'][M]>
  ) {
    return new DeployMethod<LendingContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      LendingContractArtifact,
      LendingContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return LendingContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(LendingContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'market_assets' | 'market_assets_list' | 'market_assets_list_len' | 'scaled_deposited_assets' | 'scaled_borrowed_assets' | 'scaled_total_deposited_assets' | 'scaled_total_borrowed_assets' | 'deposit_accumulators' | 'borrow_accumulators'> {
      return {
        market_assets: {
      slot: new Fr(1n),
    },
market_assets_list: {
      slot: new Fr(2n),
    },
market_assets_list_len: {
      slot: new Fr(3n),
    },
scaled_deposited_assets: {
      slot: new Fr(4n),
    },
scaled_borrowed_assets: {
      slot: new Fr(5n),
    },
scaled_total_deposited_assets: {
      slot: new Fr(6n),
    },
scaled_total_borrowed_assets: {
      slot: new Fr(7n),
    },
deposit_accumulators: {
      slot: new Fr(8n),
    },
borrow_accumulators: {
      slot: new Fr(9n),
    }
      } as ContractStorageLayout<'market_assets' | 'market_assets_list' | 'market_assets_list_len' | 'scaled_deposited_assets' | 'scaled_borrowed_assets' | 'scaled_total_deposited_assets' | 'scaled_total_borrowed_assets' | 'deposit_accumulators' | 'borrow_accumulators'>;
    }
    

  public static get notes(): ContractNotes<'UintNote'> {
    return {
      UintNote: {
          id: new NoteSelector(0),
        }
    } as ContractNotes<'UintNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_asset(market_id: field, asset_address: struct, oracle: struct, loan_to_value: integer, is_borrowable: boolean, optimal_utilization_rate: integer, under_optimal_slope: integer, over_optimal_slope: integer, deposit_cap: integer) */
    add_asset: ((market_id: FieldLike, asset_address: AztecAddressLike, oracle: AztecAddressLike, loan_to_value: (bigint | number), is_borrowable: boolean, optimal_utilization_rate: (bigint | number), under_optimal_slope: (bigint | number), over_optimal_slope: (bigint | number), deposit_cap: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** borrow_private(secret: field, to: struct, amount: integer, market_id: field, asset_address: struct) */
    borrow_private: ((secret: FieldLike, to: AztecAddressLike, amount: (bigint | number), market_id: FieldLike, asset_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** borrow_public(to: struct, amount: integer, market_id: field, asset_address: struct) */
    borrow_public: ((to: AztecAddressLike, amount: (bigint | number), market_id: FieldLike, asset_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** compute_total_deposited_assets(market_id: field, asset_address: struct, deposit_accumulator: struct) */
    compute_total_deposited_assets: ((market_id: FieldLike, asset_address: AztecAddressLike, deposit_accumulator: { value: (bigint | number), last_updated_ts: (bigint | number) }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor() */
    constructor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** deposit_private(from: struct, amount: integer, nonce: field, secret: field, on_behalf_of: field, market_id: field, collateral_asset: struct) */
    deposit_private: ((from: AztecAddressLike, amount: (bigint | number), nonce: FieldLike, secret: FieldLike, on_behalf_of: FieldLike, market_id: FieldLike, collateral_asset: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** deposit_public(amount: integer, nonce: field, on_behalf_of: field, market_id: field, collateral_asset: struct) */
    deposit_public: ((amount: (bigint | number), nonce: FieldLike, on_behalf_of: FieldLike, market_id: FieldLike, collateral_asset: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_accumulators(market_id: field, asset_address: struct) */
    get_accumulators: ((market_id: FieldLike, asset_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_position(owner: struct, market_id: field, asset_address: struct) */
    get_position: ((owner: AztecAddressLike, market_id: FieldLike, asset_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_borrowed_assets(market_id: field, asset_address: struct) */
    get_total_borrowed_assets: ((market_id: FieldLike, asset_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_deposited_assets(market_id: field, asset_address: struct) */
    get_total_deposited_assets: ((market_id: FieldLike, asset_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** liquidate_public(market_id: field, collateral_asset: struct, debt_asset: struct, user: struct, debt_to_cover: integer) */
    liquidate_public: ((market_id: FieldLike, collateral_asset: AztecAddressLike, debt_asset: AztecAddressLike, user: AztecAddressLike, debt_to_cover: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** repay_private(from: struct, amount: integer, nonce: field, secret: field, on_behalf_of: field, market_id: field, asset_address: struct) */
    repay_private: ((from: AztecAddressLike, amount: (bigint | number), nonce: FieldLike, secret: FieldLike, on_behalf_of: FieldLike, market_id: FieldLike, asset_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** repay_public(amount: integer, nonce: field, owner: struct, market_id: field, asset_address: struct) */
    repay_public: ((amount: (bigint | number), nonce: FieldLike, owner: AztecAddressLike, market_id: FieldLike, asset_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_notes() */
    sync_notes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_accumulators(market_id: field, asset_address: struct) */
    update_accumulators: ((market_id: FieldLike, asset_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw_private(secret: field, to: struct, amount: integer, market_id: field, collateral_asset: struct) */
    withdraw_private: ((secret: FieldLike, to: AztecAddressLike, amount: (bigint | number), market_id: FieldLike, collateral_asset: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw_public(to: struct, amount: integer, market_id: field, collateral_asset: struct) */
    withdraw_public: ((to: AztecAddressLike, amount: (bigint | number), market_id: FieldLike, collateral_asset: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
